name: CI/CD Workflow for WordPress with Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  setup-wordpress:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y apache2 php libapache2-mod-php php-mysql mysql-server wget unzip
        
    - name: Start MySQL Service
      run: |
        sudo service mysql start
        sudo mysql -u root -e "CREATE DATABASE wordpress;"
        sudo mysql -u root -e "CREATE USER 'wp_user'@'localhost' IDENTIFIED BY 'password';"
        sudo mysql -u root -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wp_user'@'localhost';"
        sudo mysql -u root -e "FLUSH PRIVILEGES;"
    
    - name: Download and Install WordPress
      run: |
        wget https://wordpress.org/latest.zip
        unzip latest.zip
        sudo mv wordpress /var/www/html/
        sudo chown -R www-data:www-data /var/www/html/wordpress
        
    - name: Configure WordPress
      run: |
        cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
        sed -i 's/database_name_here/wordpress/' /var/www/html/wordpress/wp-config.php
        sed -i 's/username_here/wp_user/' /var/www/html/wordpress/wp-config.php
        sed -i 's/password_here/password/' /var/www/html/wordpress/wp-config.php
        
    - name: Start Apache Server
      run: |
        sudo service apache2 start

    - name: Verify WordPress Setup
      run: curl -I http://localhost/wordpress
      
  run-cypress-tests:
    runs-on: ubuntu-latest
    needs: setup-wordpress

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Cypress dependencies
      run: |
        npm install
        npx cypress install
        
    - name: Run Cypress Tests
      run: |
        npx cypress run --spec "cypress/integration/*"
      
    - name: Share Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: cypress/reports/
