name: MySQL Docker Setup and Report

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code (optional)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up MySQL container using Docker
      - name: Set up MySQL Docker container
        run: |
          # Pull the official MySQL Docker image
          docker pull mysql:8.0

          # Run MySQL container with environment variables for root password
          docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=root_password -d mysql:8.0

          # Wait for MySQL to be ready (give it some time to initialize)
          sleep 30

      # Step 3: Create Database and Table in MySQL container
      - name: Create Database and Insert Data
        run: |
          # Create database and table using Docker MySQL client
          docker exec -i mysql-container mysql -u root -proot_password -e "CREATE DATABASE IF NOT EXISTS test_db;"
          docker exec -i mysql-container mysql -u root -proot_password -e "CREATE TABLE IF NOT EXISTS test_db.users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), email VARCHAR(255));"
          docker exec -i mysql-container mysql -u root -proot_password -e "INSERT INTO test_db.users (name, email) VALUES ('John Doe', 'john@example.com');"
          docker exec -i mysql-container mysql -u root -proot_password -e "INSERT INTO test_db.users (name, email) VALUES ('Jane Smith', 'jane@example.com');"

      # Step 4: Show Databases and Generate Report
      - name: Show Databases and Generate Report
        run: |
          # Show databases and generate report from the container
          docker exec -i mysql-container mysql -u root -proot_password -e "SHOW DATABASES;"
          docker exec -i mysql-container mysql -u root -proot_password -e "SELECT * FROM test_db.users;" > report.txt

      # Step 5: Upload the Report as Artifact
      - name: Upload MySQL Report
        uses: actions/upload-artifact@v3
        with:
          name: mysql-report
          path: report.txt
