name: MySQL Database Setup and Status Check

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Install MySQL
      - name: Install MySQL
        run: |
          # Update and Install MySQL Server
          sudo apt-get update
          sudo apt-get install -y mysql-server

      # Step 2: Start MySQL Service
      - name: Start MySQL Service
        run: |
          # Start MySQL Service
          sudo service mysql start

          # Check MySQL Service Status
          sudo service mysql status

      # Step 3: Show Databases and Create Database
      - name: Show Databases and Create test_db
        run: |
          # Show existing databases
          sudo mysql -e "SHOW DATABASES;"

          # Create Database if it doesn't exist
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS test_db;"

          # Show Databases again to confirm creation
          sudo mysql -e "SHOW DATABASES;"

      # Step 4: Upload the Report as Artifact (optional)
      - name: Upload MySQL Report
        uses: actions/upload-artifact@v3
        with:
          name: mysql-report
          path: report.txt
