name: MySQL Setup Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code (optional, if you need code for other purposes)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install MySQL and start the service
      - name: Install and Start MySQL
        run: |
          # Update and Install MySQL Server
          sudo apt-get update
          sudo apt-get install -y mysql-server

          # Start MySQL Service
          sudo service mysql start

          # Check MySQL Status
          sudo service mysql status

          # Check if MySQL is running
          sudo mysql -e "SELECT 1;" || echo "MySQL is not working"

          # Display MySQL version to confirm it's installed and running
          mysql --version
