name: Simple MySQL Setup and Report

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install MySQL Server
      - name: Install MySQL Server
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server

      # Step 2: Start MySQL Service
      - name: Start MySQL Service
        run: |
          sudo service mysql start

      # Step 3: Check MySQL Status
      - name: Check MySQL Status
        run: |
          sudo service mysql status || echo "MySQL is not running"

      # Step 4: Create a Database and Table, Insert Data
      - name: Create Database and Insert Data
        run: |
          # Attempt to create a database and table
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS test_db;"
          sudo mysql -e "CREATE TABLE IF NOT EXISTS test_db.users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), email VARCHAR(255));"
          sudo mysql -e "INSERT INTO test_db.users (name, email) VALUES ('John Doe', 'john@example.com');"
          sudo mysql -e "INSERT INTO test_db.users (name, email) VALUES ('Jane Smith', 'jane@example.com');"

      # Step 5: Check Databases
      - name: Show Existing Databases
        run: |
          sudo mysql -e "SHOW DATABASES;"

      # Step 6: Generate MySQL Report (Plain Text)
      - name: Generate MySQL Report
        run: |
          sudo mysql -e "SELECT * FROM test_db.users;" > report.txt

      # Step 7: Upload Report as Artifact
      - name: Upload MySQL Report
        uses: actions/upload-artifact@v3
        with:
          name: mysql-report
          path: report.txt
