name: WordPress CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: SSH into the App Server and Set Up WordPress
      - name: SSH into App Server and Set Up WordPress
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 172.22.26.65
          username: ubuntu # Replace with your server's username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Add your SSH private key to GitHub Secrets
          port: 22
          script: |
            # Update and Install Dependencies
            sudo apt-get update
            sudo apt-get install -y mysql-server php php-mysql unzip curl

            # Configure MySQL
            sudo service mysql start
            sudo mysql --user=root <<EOF
            UPDATE mysql.user SET plugin = 'mysql_native_password' WHERE user = 'root';
            ALTER USER 'root'@'localhost' IDENTIFIED BY 'root_password';
            FLUSH PRIVILEGES;
            CREATE DATABASE wordpress;
            CREATE USER 'runner'@'localhost' IDENTIFIED BY 'runner_password';
            GRANT ALL PRIVILEGES ON wordpress.* TO 'runner'@'localhost';
            FLUSH PRIVILEGES;
            EOF

            # Verify MySQL Setup
            sudo mysql -uroot -proot_password -e "SHOW DATABASES;" || echo "Failed to show databases as root user"
            sudo mysql -urunner -prunner_password -e "SHOW DATABASES;" || echo "Failed to show databases as runner user"

            # Download and Configure WordPress
            curl -O https://wordpress.org/latest.tar.gz
            tar -xzf latest.tar.gz
            sudo mv wordpress/* /var/www/html/
            sudo chown -R www-data:www-data /var/www/html
            sudo cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
            sudo sed -i "s/database_name_here/wordpress/" /var/www/html/wp-config.php
            sudo sed -i "s/username_here/runner/" /var/www/html/wp-config.php
            sudo sed -i "s/password_here/runner_password/" /var/www/html/wp-config.php

            # Start Apache Server (Optional: Replace with your actual web server setup)
            sudo apt-get install -y apache2
            sudo service apache2 start

            # Test WordPress Accessibility
            for i in {1..10}; do
              if curl -s http://127.0.0.1/wp-admin/install.php; then
                echo "WordPress is ready!"
                break
              else
                echo "Retrying WordPress setup..."
                sleep 5
              fi
            done
