name: WordPress CI/CD with Cypress

on:
  push:
    branches:
      - main

jobs:
  setup-wordpress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup WordPress Environment
      run: |
        # Install required dependencies
        sudo apt-get update
        sudo apt-get install -y apache2 php libapache2-mod-php php-mysql mysql-server wget unzip
        
        # Start MySQL service
        sudo service mysql start
        sleep 10  # Allow MySQL to initialize
        
        # Configure root user for password-based authentication
        #sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'rootpassword';"
        #sudo mysql -e "FLUSH PRIVILEGES;"
        
        # Test the connection
        sudo mysql -u root -prootpassword -e "SHOW DATABASES;"
        
        # Set up WordPress database and user
        sudo mysql -u root -prootpassword -e "CREATE DATABASE wordpress;"
        sudo mysql -u root -prootpassword -e "CREATE USER 'wp_user'@'localhost' IDENTIFIED BY 'password';"
        sudo mysql -u root -prootpassword -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wp_user'@'localhost';"
        #sudo mysql -u root -prootpassword -e "FLUSH PRIVILEGES;"
        
        # Download and configure WordPress
        wget https://wordpress.org/latest.zip
        unzip latest.zip
        sudo mv wordpress /var/www/html/
        sudo chown -R www-data:www-data /var/www/html/wordpress
        sudo cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
        sudo sed -i 's/database_name_here/wordpress/' /var/www/html/wordpress/wp-config.php
        sudo sed -i 's/username_here/wp_user/' /var/www/html/wordpress/wp-config.php
        sudo sed -i 's/password_here/password/' /var/www/html/wordpress/wp-config.php
        
        # Start Apache server
        sudo service apache2 start

    - name: Verify WordPress Setup
      run: curl -I http://localhost/wordpress
