name: WordPress CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install MySQL and Configure No-Password Root Access
      - name: Install and Configure MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'auth_socket';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      # Step 3: Verify MySQL Service and Access
      - name: Verify MySQL Service
        run: |
          sudo mysql -u root -e "SHOW DATABASES;"

      # Step 4: Create WordPress Database
      - name: Create WordPress Database
        run: |
          sudo mysql -u root -e "CREATE DATABASE wordpress;"

      # Step 5: Install PHP and Dependencies
      - name: Install PHP and dependencies
        run: |
          sudo apt-get install -y php php-mysql unzip curl

      # Step 6: Download and Configure WordPress
      - name: Set up WordPress
        run: |
          curl -O https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          mv wordpress/* .
          cp wp-config-sample.php wp-config.php
          sed -i "s/database_name_here/wordpress/" wp-config.php
          sed -i "s/username_here/root/" wp-config.php
          sed -i "s/password_here//" wp-config.php
          php -S 127.0.0.1:8080 &

      # Step 7: Wait for WordPress to be Ready
      - name: Wait for WordPress Setup
        run: |
          for i in {1..10}; do
            curl -s http://127.0.0.1:8080/wp-admin/install.php && break
            sleep 5
          done
