name: WordPress CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install, Configure, and Start MySQL
      - name: Install and Configure MySQL
        run: |
          # Update and Install MySQL Server
          sudo apt-get update
          sudo apt-get install -y mysql-server

          # Start MySQL Service
          sudo service mysql start

          # Check MySQL Status
          sudo service mysql status

          # MySQL Commands to Setup Database and User
          sudo mysql -e "SHOW DATABASES;"
          sudo mysql -e "CREATE DATABASE wordpress;"
          sudo mysql -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'runner'@'localhost' IDENTIFIED BY 'runner_password';"
          sudo mysql -e "FLUSH PRIVILEGES;"

    
