name: Check MySQL Status and Generate Report

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Install MySQL
      - name: Install MySQL
        run: |
          # Update and Install MySQL Server
          sudo apt-get update
          sudo apt-get install -y mysql-server

      # Step 2: Start MySQL Service
      - name: Start MySQL Service
        run: |
          # Start MySQL Service using systemctl
          sudo service mysql status
          sudo  service start mysql

          # Check if MySQL service started correctly
          sudo service status mysql || echo "MySQL did not start correctly" > mysql_status_error.txt

      # Step 3: Verify MySQL Connection and Create Report
      - name: Verify MySQL Connection and Create Report
        run: |
          # Attempt a MySQL connection and run a simple query
          if sudo mysql -e "SELECT 1;" > /dev/null 2>&1; then
            echo "MySQL is working" > result_report.txt
          else
            echo "MySQL is not working" > result_report.txt
          fi

          # Add MySQL service status to the report
          echo "\nMySQL Service Status:" >> result_report.txt
          cat mysql_status_error.txt >> result_report.txt || echo "No service status available" >> result_report.txt

      # Step 4: Upload the Report as Artifact
      - name: Upload MySQL Report
        uses: actions/upload-artifact@v3
        with:
          name: mysql-status-report   # Artifact name
          path: result_report.txt     # Path to the report file
