name: WordPress CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install, Configure, and Start MySQL
      - name: Install and Configure MySQL
        run: |
          # Update and Install Dependencies
          sudo apt-get update
          sudo apt-get install -y mysql-server php php-mysql unzip curl apache2 libmysqlclient-dev

          # Start MySQL Service with systemctl
          sudo systemctl enable mysql
          sudo systemctl start mysql

          # Check MySQL Logs if service fails to start
          sudo journalctl -xe | grep mysql

          # Ensure MySQL is running
          sudo systemctl status mysql

          # Configure MySQL
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS wordpress;"
          #sudo mysql -e "CREATE USER IF NOT EXISTS 'runner'@'localhost' IDENTIFIED BY 'runner_password';"
          #sudo GRANT ALL PRIVILEGES ON wordpress.* TO 'runner'@'localhost' IDENTIFIED BY 'runner_password';
          #sudo mysql -e "FLUSH PRIVILEGES;"

          # Verify MySQL Setup
          sudo mysql -e "SHOW DATABASES;"

      # Step 3: Download and Configure WordPress
      - name: Download and Configure WordPress
        run: |
          # Download and Extract WordPress
          curl -O https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          sudo mv wordpress/* /var/www/html/

          # Set Proper Permissions
          sudo chown -R www-data:www-data /var/www/html

          # Configure WordPress
          sudo cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
          sudo sed -i "s/database_name_here/wordpress/" /var/www/html/wp-config.php
          sudo sed -i "s/username_here/runner/" /var/www/html/wp-config.php
          sudo sed -i "s/password_here/runner_password/" /var/www/html/wp-config.php

      # Step 4: Start Apache Server
      - name: Start Apache Server
        run: |
          sudo service apache2 start

      # Step 5: Verify WordPress Installation
      - name: Verify WordPress Installation
        run: |
          for i in {1..10}; do
            if curl -s http://127.0.0.1/wp-admin/install.php; then
              echo "WordPress is ready!"
              exit 0
            else
              echo "Retrying WordPress setup..."
              sleep 5
            fi
          done
          echo "WordPress setup failed!" && exit 1
