name: Simple MySQL Setup and Report

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code (optional)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install and Start MySQL
      - name: Install and Start MySQL
        run: |
          # Update and Install MySQL Server
          sudo apt-get update
          sudo apt-get install -y mysql-server

          # Start MySQL Service
          sudo service mysql start

          # Check MySQL Service Status
          sudo service mysql status

          # Verify MySQL is working
          sudo mysql -e "SELECT 1;" || echo "MySQL is not working"

      # Step 3: Create Database, Table, and Insert Data
      - name: Create Database, Table, and Insert Data
        run: |
          # Create Database
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS test_db;"
          
          # Create Table
          sudo mysql -e "CREATE TABLE IF NOT EXISTS test_db.users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), email VARCHAR(255));"

          # Insert Data
          sudo mysql -e "INSERT INTO test_db.users (name, email) VALUES ('John Doe', 'john@example.com');"
          sudo mysql -e "INSERT INTO test_db.users (name, email) VALUES ('Jane Smith', 'jane@example.com');"

      # Step 4: Generate MySQL Report (with results in plain text)
      - name: Generate MySQL Report
        run: |
          # Query the database and output the result to a text file
          sudo mysql -e "SELECT * FROM test_db.users;" > report.txt

      # Step 5: Upload the Report as Artifact
      - name: Upload MySQL Report
        uses: actions/upload-artifact@v3
        with:
          name: mysql-report   # Artifact name
          path: report.txt     # Path to the report file
